image: node:latest

stages:
  - build

before_script:
  - yarn install

build:
  stage: build
  variables:
    NODE_ENV: production
  script:
    - export NODE_ENV=production
    - yarn run build:webpack
  artifacts:
    paths:
      - dist/*